name: build

on:
  push:

  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: install package
        run: yarn

      - name: build project
        run: yarn build
